# Generated by Django 4.0.4 on 2023-05-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID autoincrementable del producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
            ],
        ),
    ]
