# Generated by Django 4.0.4 on 2023-07-09 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('boleta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID  del carrito')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad productos')),
                ('total', models.IntegerField(verbose_name='Total boleta')),
                ('idEstado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.estadoc')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
