# Generated by Django 4.0.4 on 2023-07-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total boleta'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total boleta'),
        ),
    ]
