# Generated by Django 4.0.4 on 2023-07-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_boleta_total_alter_carrito_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='nro_pedido',
            field=models.IntegerField(default=1, verbose_name='numero de pedido'),
        ),
    ]
