# Generated by Django 4.0.4 on 2023-07-10 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_boleta_nro_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='idEstado',
        ),
    ]
