# Generated by Django 4.0.4 on 2023-07-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_carrito_idestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio producto'),
        ),
    ]
