# Generated by Django 4.0.4 on 2023-07-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_boleta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total boleta'),
        ),
    ]
