# Generated by Django 4.0.4 on 2023-07-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_boleta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Color'),
        ),
    ]
